import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col">
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var el=document.getElementById('pronounceRootElement');if(el)el.remove();document.querySelectorAll('.pronounceRootElementItem').forEach(function(n){n.remove()});document.querySelectorAll('audio').forEach(function(a){try{if(a && a.style && a.style.position==='fixed')a.remove()}catch(e){}});}catch(e){} })();`,
          }}
        />
        {children}
      </body>
    </html>
  );
}
